# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["runtime", "compiler"]
resolver = "2"

[profile.release]
strip = true
lto = true